language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: "ner_duckling_http"
  url: "http://0.0.0.0:8000"
  locale: "da_DK"
  dimensions: ["time"]
# this is using the spacy sklearn pipeline, adding duckling
# all components will use their default values
#- name: "nlp_spacy"
#- name: "tokenizer_spacy"
#- name: "intent_featurizer_spacy"
#- name: "ner_crf"
#- name: "ner_synonyms"
#- name: "intent_classifier_sklearn"
#- name: "ner_duckling_http"
#  url: "http://duckling:8000"
  # dimensions to extract
# dimensions: ["time"]



